### ISSUE TITLE
Uninstalling “dart-tools” failed

### ISSUE THREAD

**Issue by othpiik** [radicaled/dart-tools#101]
```
Uninstalling “dart-tools” failed.Hide output…
Failed to delete dart-tools: Does not exist
```

I try to install dart-tools but autocompletion not working and wanna uninstall but 
`Failed to delete dart-tools: Does not exist`

**Comment by radicaled** [comment]
You can check ~/.atom/ to see if dart-tools exists somewhere within that directory tree. If so, you can delete it without a problem.

Safer is to use https://atom.io/packages/dartlang instead -- this project is dead.
