### ISSUE TITLE
Linting should work without a pubspec.yaml

### ISSUE THREAD

**Issue by sethladd** [radicaled/dart-tools#23]
Can we get linting/analysis to work if my Dart project doesn't have a pubspec.yaml ? Thanks!

**Comment by radicaled** [comment]
I'm not sure how to detect a Dart project without the presence of a `pubspec.yaml` file present. Do you have any ideas?

**Comment by devoncarew** [comment]
Partially addressed in #39 - we now check for the presence of a `.packages` file.

**Comment by radicaled** [comment]
Who generates `.packages`? If it's `pub`, then isn't this the same thing?

**Comment by radicaled** [comment]
OmniSharp (https://github.com/OmniSharp/omnisharp-atom) deals with this by detecting the user opening a .cs or .scriptcs file and then booting the server on demand.

I think we could do this too, but it will require some changes to the codebase.

1. Start `analysis_server` on demand.
2. Update how we notify the user whether the `analysis_server` is running or not. Possibly follow OmniSharp on this and display an icon in the toolbar that changes state when the server is running.

We'd also have to figure out how to deal with solo Dart files that are opened outside the context of the current Atom project. The logic might be, "If the open Dart file is not a child of any of the current projects, do not run any analysis on it."

**Comment by devoncarew** [comment]
> and display an icon in the toolbar that changes state when the server is running.

I think it would be great to know when the analysis server is busy. Often the issue count is changing and I don't know if the AS is still processing or all the errors are displayed. It would be great to have a debounced spinner that was on when the AS was processing changes.

> We'd also have to figure out how to deal with solo Dart files that are opened outside the context of the current Atom project. The logic might be, "If the open Dart file is not a child of any of the current projects, do not run any analysis on it."

+1. singleton dart files should have (gracefully) reduced dart support. The AS server might only be told about top-level projects that had pubspec.yaml or .packages files.

**Comment by radicaled** [comment]
> I think it would be great to know when the analysis server is busy. Often the issue count is changing and I don't know if the AS is still processing or all the errors are displayed. It would be great to have a debounced spinner that was on when the AS was processing changes.

I agree. It'd be great to have a colored logo that pulsed like the OmniSharp logo to signal that -- unobtrusive but present. We can't re-use any of Dart logos for this: they're CC-BY 3.0, but there's a guidelines section that runs counter to the license, so I don't want to stick my hand into that mess.

We can probably use the Octocat spinner that's bundled with Atom for now.

**Comment by sethladd** [comment]
Curious, why does CC-BY 3.0 prevent you from using the logo?

**Comment by radicaled** [comment]
It's not the CC-BY 3.0 license -- it's the "Guidelines" section at https://www.dartlang.org/logos/

CC-BY 3.0 is essentially letting people go wild with assets as long as you do attribution: https://creativecommons.org/licenses/by/3.0/us/

So that runs counter with the entire "Guidelines" section -- you can't make me adhere to a particular color scheme if it's CC-BY 3.0. 

The implication I'm getting from that logos page is that those assets aren't really meant to be CC-BY 3.0 if you're doling out guidelines on how to use them with regards to color, sizing, etc. I might be taking "guidelines" too strictly, though.

**Comment by sethladd** [comment]
Thanks for the analysis. The guidelines are there to make sure people don't morph the logo into something it's not. But we do want people to feel free to use the logo on tshirts, stickers without having to ask us first.

Maybe we technically need a different license. No one has brought it up until now.

It doesn't sound like the guidelines prohibit you from pulsing the logo, though, since you'd be keeping it at the same aspect ratio (presumably?)

**Comment by radicaled** [comment]
> It doesn't sound like the guidelines prohibit you from pulsing the logo, though, since you'd be keeping it at the same aspect ratio (presumably?)

I wouldn't change the aspect ratio, but I'd be breaking this guideline for sure: "Do not stray from the color palette."

If I was going to represent the analysis server with an icon, there'd be a gray-scale state which meant "off", a colored state which meant "on but idle", and a pulsing state which meant "on and working". The idle state and the working state would change the color palette, I think, with regards to hue / intensity.

**Comment by sethladd** [comment]
Ah, thanks for the clarification. Yes, that would go against the guidelines. You have a Plan B ?

**Comment by radicaled** [comment]
I'm just going to toss something together and someone else can come along and change it after they get tired of staring at it for like five hours.

Worked with devoncarew.

**Comment by radicaled** [comment]
This shipped in v0.9.12.

I'm going to track the "process monitor" icon in another issue.
