### ISSUE TITLE
Q: How do I manually run pub get ?

### ISSUE THREAD

**Issue by sethladd** [radicaled/dart-tools#24]
N00b Atom user here...

Thanks!

**Comment by radicaled** [comment]
Command Palette is CTRL+SHIFT+P or CMD+SHIFT+P.

So, summon the Command Palette and type "Pub" and you should see it. If not, that means the Atom package crashed at some point and wasn't able to register custom commands.

If that looks like the like the case, summon the Command Palette, type "Dev" and look for "Toggle Windows Dev Tools."

It'll summon the Chromium Dev Tools and you'll probably see a stacktrace in the console.

**Comment by radicaled** [comment]
Assuming this works now. Reopen if it doesn't!
