### ISSUE TITLE
Support Windows!

### ISSUE THREAD

**Issue by radicaled** [radicaled/dart-tools#28]
The tool executor assumes OS X / Linux conventions. We need to support `dart.exe` and `pub.bat` instead of `dart` and `pub`. This is a bit of a regression: now that we don't try to automatically detect the dart executable, we have to append the file extensions on manually under windows.

Related to #26, and maybe #25 and #24.

**Comment by hectorfhurtado** [comment]
Its necesary check on __analysis_server.coffee__ too

**Comment by hectorfhurtado** [comment]
Thanks. It's pub getting right. Now I'm looking in to why It's not analyzinfg my .dart file

**Comment by hectorfhurtado** [comment]
Oops, how can I undo my 'commit'?

**Comment by radicaled** [comment]
No test windows box available for me right now, so please let me know what you find out. :)

**Comment by hectorfhurtado** [comment]
I ran `dart.exe snapshots\analysis_server.dart.snapshot file` and It runs on my terminal but It isn't started on Atom.

I'm off for today and tomorrow I'm not on my windows machine, so, until Thursday I can test again.

**Comment by hectorfhurtado** [comment]
Hi, now It works! On utils.coffee, just change line 70 from `execPath = path.join(sdkPath, 'bin', dart')` to `execPath = 'dart'` and It solves #25 too

**Comment by radicaled** [comment]
Thanks -- I'll be patching this shortly. I'll probably be removing some of that "where"-based code, because that's some legacy stuff I never cleaned up.

**Comment by radicaled** [comment]
I've just published v0.9.8 -- it'd be great if you could take a look, @hectorfhurtado and let me know how it works. You've been a great help in getting Windows support nailed down, especially since I don't do any development under Windows so I'm totally flying blind. :)

**Comment by hectorfhurtado** [comment]
Hi, It's working very well thanks. I really want to use this plugin because I dislike Java IDEs ( they block my PC ) and atom helps me to view your code and I can make tweaks :)

I'm using now v0.9.10

**Comment by radicaled** [comment]
Thanks for the verification!
