### ISSUE TITLE
the Dart Tools panel is large and doesn't contain much info

### ISSUE THREAD

**Issue by devoncarew** [radicaled/dart-tools#30]
![screen shot 2015-05-21 at 3 43 46 pm](https://cloud.githubusercontent.com/assets/1269969/7760433/4b0b2f0a-ffd0-11e4-8922-c9da03753887.png)

You might want to reduce the height, make it only show when there are errors, or perhaps contribute a much smaller UI to the status line?

**Comment by radicaled** [comment]
I'm not really a UI guy, so I just sort of threw it together using Atom's default classes. I'll spend some time thinking about how to improve it.

**Comment by devoncarew** [comment]
I'll play with the css (less?) and open a PR if I make progress :)

**Comment by radicaled** [comment]
(CTRL/CMD)+SHIFT+P, toggle dev tools, and you can do it interactively. :)
