### ISSUE TITLE
TODOs are listed as errors

### ISSUE THREAD

**Issue by devoncarew** [radicaled/dart-tools#31]
![screen shot 2015-05-21 at 7 18 45 pm](https://cloud.githubusercontent.com/assets/1269969/7762921/49906e24-ffee-11e4-9674-4ed5e1fcca9a.png)

I have 9 todos in my project and the status line says I have 9 errors -

**Comment by radicaled** [comment]
Yeah, I'm not sure how to handle this currently. The analysis server reports "TODOs" along with hints, warnings, and errors, so right now I'm naively taken the analysis server's word for it and just displaying whatever they give us.

Suggestions? I suppose I could rename "Errors" to something else, like whatever WebStorm's panel calls it.

**Comment by devoncarew** [comment]
There's probably a type field in with the info that's coming back. You might want a summary like `4 errors and 1 warning` (and completely filter out the infos - they're less actionable).

**Comment by devoncarew** [comment]
Or rather, the infos would show up in a full listing, but might not in a short textual summary.

**Comment by radicaled** [comment]
That sounds good to me. I'll look into it.
