### ISSUE TITLE
Errors when using dart installed from Homebrew

### ISSUE THREAD

**Issue by justinfagnani** [radicaled/dart-tools#37]
I followed the installation instructions here: https://www.dartlang.org/downloads/mac.html

and how have `dart` and `pub` in `/usr/local/bin`. I had to set my SDK directory to `/usr/local`, which seems odd, but that allowed dart-tools to find the `dart` binary. It can't find the analysis server though.

**Comment by devoncarew** [comment]
I think you'll need to set the sdk path to something like: `/Users/foobar/homebrew/Cellar/dart/1.10.0/`.

**Comment by radicaled** [comment]
`ls -asl /usr/local/bin | grep dart` will tell you where `dart` is symlinked to, which will help you find the Dart SDK.

However, if you always want to use the newest version of Dart with dart-tools, use this as the SDK path:

`/usr/local/opt/dart/libexec`

`/usr/local/opt/dart` is always symlinked to latest Dart (unless you specified another version of Dart via `brew`), and `libexec` is where all the Dart SDK files, not just its binary files, exist.

**Comment by sethladd** [comment]
I point all my editors to `/usr/local/opt/dart/libexec` and I use homebrew. :)

**Comment by radicaled** [comment]
@justinfagnani 

All set?

**Comment by justinfagnani** [comment]
Yeah, `/usr/local/opt/dart/libexec` seems to work. It'd be nice to have some instructions on that, either with dart-tools, or on the dartlang.org page that references Homebrew. @sethladd

**Comment by sethladd** [comment]
I added that note to the Sublime setup. Which I know doesn't help here :) I'll see where I can suggest that change for Atom. Thanks for the feedback!

**Comment by radicaled** [comment]
Looks like https://github.com/radicaled/dart-tools/pull/70 covers it thanks to @sethladd, so I'll close this issue.

Thanks!
