### ISSUE TITLE
`Utils.isDartProject` only checks the first project

### ISSUE THREAD

**Issue by devoncarew** [radicaled/dart-tools#38]
Only one Dart project is analyzed in the atom workspace, and only if it's the first one in the list:

```
rootDirectory = atom.project.getDirectories()[0]
```

dart-tools should probably analyze every dart project in the workspace.

**Comment by radicaled** [comment]
Some work on this done in 77d97f26dfad159fda572dc06726adbc192dc32e . What's missing: running Pub commands contextually (ie, for project A but not project B). Right now they'll just run for the first project they find -- same as behavior before.

**Comment by radicaled** [comment]
v0.9.12 now supports running Pub on multiple projects, which now completes this.
