### ISSUE TITLE
set up a CI?

### ISSUE THREAD

**Issue by devoncarew** [radicaled/dart-tools#46]
This repo: https://github.com/atom/ci has some good info about setting up a CI for atom plugin using travis.

**Comment by radicaled** [comment]
dart-tools... has no tests: #14.

Yet.

**Comment by devoncarew** [comment]
Sure, but it could do things like run lints. And having a CI makes tests more meaningful; you're more incentivized to write tests.

**Comment by radicaled** [comment]
Heh, you greatly underestimate my potential for laziness when it comes to code I'm not being paid to produce.

In all seriousness, I'll accept a PR for it. It's low on my priority list otherwise, since there's no pre-existing test suite.

**Comment by devoncarew** [comment]
All done except for the final hook-up. @radicaled, you'll need to go to here https://travis-ci.org/radicaled/dart-tools or similar, and turn on travis for the `dart-tools` repo. Once it's enabled I'll look at any initial build failures that crop up.

**Comment by radicaled** [comment]
I've enabled it -- the next push should trigger a build.

**Comment by devoncarew** [comment]
Success!

https://travis-ci.org/radicaled/dart-tools/builds/63805925
