### ISSUE TITLE
consider using the `linter` plugin for error visualization

### ISSUE THREAD

**Issue by devoncarew** [radicaled/dart-tools#49]
The `linter` plugin has very nice visualization of errors. It has gutter decorations, nice tooltips, and an optional error panel at the bottom of the screen. We should consider adding a linter contribution from dart-tools. One thing to work around would be that `linter` expects file lints to be a one time operation. When a file changes they can shell out to a CLI tool and collect any issues.

With the analysis server, file changes can cause non-local changes in issues for other files. So we'd need a way of updating the issues for files other than the current one. Not sure is this use case is covered by the linter API.

**Comment by radicaled** [comment]
It looks like the `linter` guys are working on a v2 of their plugin that allows for pushing errors to the linter rather than pulling them: https://github.com/AtomLinter/Linter/issues/387

The push v pull issue was my main problem when I was evaluating using the `linter` package vs rolling my own. The second was the massive number of open & stale issues on their repository.

Either way, I think re-evaluating the `linter` package when their v2.0 lands is a good idea.

**Comment by devoncarew** [comment]
I'll close this for now and we can re-evaluate later. I have some in-flight changes to tweak the error display. I think it'd make sense to use `linter` if much of the atom community uses it - it'd give people one place to tweak error display preferences.

**Comment by devoncarew** [comment]
They may be replacing `linter` with `linter-plus` - it's not clear. https://github.com/AtomLinter/linter-plus

It doesn't look like that newer API supports push lints.

**Comment by radicaled** [comment]
I was going to open an issue about a push-based API but I see that you've done that already.

Let's watch `linter-plus` and see how it shakes out.

(not sure why I thought `linter` wanted a push-based API)

¯\_(ツ)_/¯

**Comment by devoncarew** [comment]
Yeah, that conversation didn't go well. I'm pretty sure his implementation won't work well if linting file A and trying to modify the lints for file B. But I agree, something to watch to see how it pans out.

**Comment by radicaled** [comment]
Looks like `linter-plus` already does what we need? https://github.com/AtomLinter/linter-plus/issues/10#issuecomment-106620370

**Comment by devoncarew** [comment]
Great!

I don't believe it's published yet (https://atom.io/packages/search?q=linter-plus) - hopefully will be shortly.

Do you know, if we depend on it in the `package.json` file, does it get installed for the user automatically when `dart-tools` is installed?

**Comment by steelbrain** [comment]
You don't depend on it in your package.json, You ask the user to install if it's not installed already, like done in https://github.com/steelbrain/Atom-Hack/blob/rewrite/lib/atom-hack.coffee#L3
