### ISSUE TITLE
Analysis server start

### ISSUE THREAD

**Issue by knownasilya** [radicaled/dart-tools#63]
The analysis server shouldn't start when you open the editor, but only when you start working with dart files.

**Comment by radicaled** [comment]
What's the purpose of delaying the analysis server start up if you've opened a project that is most definitely a Dart project?

**Comment by knownasilya** [comment]
It starts when you open atom, even if you have no projects or files open. It doesn't seem desirable to start the server when dealing with non-dart projects.

**Comment by radicaled** [comment]
Ah, it's only supposed to start automatically if there `pubspec.yaml` or `.packages` is present in a project root. 

I'll look into this.

**Comment by radicaled** [comment]
Actually, this is fixed in the current unpublished version of the Atom plugin. I'll bump this issue when the newest version is resolved so you know when to upgrade.

**Comment by radicaled** [comment]
This should be resolved in 0.9.12

**Comment by knownasilya** [comment]
Thanks!
