### ISSUE TITLE
dart-tools is very aggressive about analyzing

### ISSUE THREAD

**Issue by devoncarew** [radicaled/dart-tools#66]
It's analyzing as I'm typing, _while_ I'm still typing a word :)

I think we want to dial it back so that it doesn't analyze until there's a pause in the typing. I'm not sure where that's set currently. On other tools, I've used reconciliation delays of 500ms - 1.2 seconds.

**Comment by radicaled** [comment]
Analyzing or autocompleting?

Autocomplete happens every keydown, but analyzing should only happen when TextEditor.onDidContentsChange (?) is fired, which is supposed to have a 500ms delay on it.

Well, it had that 500ms delay before the big API change. We can use `_.debounce` here if necessary.

**Comment by devoncarew** [comment]
It's for analyzing. It's just anecdotal - I haven't looked at how long the delay is. But it seems a tad quick.

**Comment by radicaled** [comment]
Looks like they split out the behavior I was relying on into two separate callbacks, and I used the wrong one. onDidStopChanging is what I meant to subscribe to. Since it waits until 300ms _after_ the last change, this might affect responsiveness if someone is typing a lot - what do you think?

**Comment by devoncarew** [comment]
300ms after the last change sounds fine to me. If I remember correctly, Eclipse defaults to 500ms. In dartpad we use 1.2 sec. I look at it as a balance between giving them very quick feedback, and penalizing them for typing too slow (showing an analysis error in the middle of them typing an identifier).

**Comment by radicaled** [comment]
Hm... I was wrong about being wrong: https://github.com/radicaled/dart-tools/blob/master/lib/buffer_update_component.coffee#L8

So it does wait 300ms after typing after all. The delay is too small, I guess: the new delay is around 550ms to 1s, depending on when the event was triggered and if the user kept typing afterward.

**Comment by hectorfhurtado** [comment]
Hi, could it be configurable on settings? as @devoncarew wrote, if I type slowly I could be penalized. Up until now, writing some code became really slow as analyzer was doing it's thing raising 7 ( up to 14 once ) issues, different ones with each keystroke.

Great plugin by the way

**Comment by radicaled** [comment]
@hectorfhurtado I've bumped up the analysis delay in #68; we'll wait for some feedback and see what happens. If people have a lot of differing opinions then we can expose it as an option on the settings page.

**Comment by radicaled** [comment]
Closing this one for now; will revisit in future if it turns out the new timers are too long.
