### ISSUE TITLE
assert word is not highlighting

### ISSUE THREAD

**Issue by sethladd** [radicaled/dart-tools#72]
assert is a reserved word. Should we highlight it?

![screen shot 2015-05-29 at 8 49 28 am](https://cloud.githubusercontent.com/assets/5479/7886554/ac82e52e-05df-11e5-8b71-9fd9f603dcae.png)

**Comment by devoncarew** [comment]
It would probably go somewhere in or around here: https://github.com/radicaled/dart-tools/blob/master/grammars/dart.cson#L113

**Comment by radicaled** [comment]
yeah, that's where keywords go.

**Comment by sethladd** [comment]
Thanks!
