### ISSUE TITLE
No warning from missing function

### ISSUE THREAD

**Issue by sethladd** [radicaled/dart-tools#74]
I was expecting to get a warning that notHere is not defined.

I have a single test.dart file on my desktop.

![screen shot 2015-05-29 at 8 59 18 am](https://cloud.githubusercontent.com/assets/5479/7886797/448fe2bc-05e1-11e5-8e9b-ce420bdc1ad6.png)

**Comment by sethladd** [comment]
here's what webstorm shows:

![screen shot 2015-05-29 at 9 02 17 am](https://cloud.githubusercontent.com/assets/5479/7886821/6ee88942-05e1-11e5-8a37-cc4a4e5397ed.png)

**Comment by radicaled** [comment]
It's probably related to this: https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/AJJTGgnzZJo

I'm trying to figure out if I'm utilizing the analyzer correctly. Right now I'm doing what I thought was the simplest thing, which was wholesale replacement of the view of a file every edit, but it seems to be losing track of issues that aren't error-level problems. So hints and warnings stop showing up.
