### ISSUE TITLE
Suggestion: Use Linter package for error highlighting

### ISSUE THREAD

**Issue by austincummings** [radicaled/dart-tools#79]
Just to keep with consistent in the Atom world, it might be best to use the [Linter](http://atom.io/packages/linter) package to provide the highlighting for dart-tools.

**Comment by radicaled** [comment]
See https://github.com/radicaled/dart-tools/issues/49 for a discussion on this.

**Comment by radicaled** [comment]
This is fixed in 0.9.18 by relying on the linter package.
