### ISSUE TITLE
Atom hangs if many dartanalyzer errors

### ISSUE THREAD

**Issue by bprosnitz** [radicaled/dart-tools#92]
If I copy some code and temporarily move it to a place which causes many errors (say from a function body temporarily to a location outside of the function body), dartanalyzer reports many errors and Atom hangs for a long time.

**Comment by radicaled** [comment]
Yeah, we've noted that there's a performance problem at the bottom of the README. This has to do with our custom error code. We'll be moving to the new linter package soon, which should alleviate this.

**Comment by radicaled** [comment]
This is fixed in 0.9.18 by relying on the linter package to do the heavy lifting.

If there are still performance problems, it's all their fault.
