### ISSUE TITLE
Uncaught TypeError: Cannot read property 'check' of undefined

### ISSUE THREAD

**Issue by ThomasLocke** [radicaled/dart-tools#96]
I get the above error when I launch Atom with dart-tools enabled. At first I get a green box that tells me that the analysis server is running, and then a second later I get a red box with this error.

This is on Slackware 14.1 x86_64.

**Atom Version**: 1.0.0
**System**: linux 3.10.53
**Thrown From**: [dart-tools](https://github.com/radicaled/dart-tools) package, v0.9.20

### Stack Trace
Uncaught TypeError: Cannot read property 'check' of undefined
```
At /home/thomas/.atom/packages/dart-tools/lib/dart-tools.coffee:118
TypeError: Cannot read property 'check' of undefined
    at /home/thomas/.atom/packages/dart-tools/lib/dart-tools.coffee:157:39
```

### Commands
```
```

### Config
```json
{
  "core": {},
  "dart-tools": {
    "dartSdkLocation": "/opt/dart/dart-sdk"
  }
}
```

### Installed Packages
```coffee
# User
dart-tools, v0.9.20

# Dev
No dev packages
```

**Comment by radicaled** [comment]
Fixed in 0.9.21.

The package should now complain that you need to install the `linter` package for linting support.
