### ISSUE TITLE
Linter exception while using dart-tools

### ISSUE THREAD

**Issue by alechenninger** [radicaled/dart-tools#98]
Please see https://github.com/AtomLinter/Linter/issues/713

Not sure if this is issue with dart-tools and/or linter, but linter works fine for non-dart projects.

**Comment by radicaled** [comment]
Looks like a regression on their side.

**Comment by alechenninger** [comment]
Yeah I think you're right, thanks for quick response

**Comment by radicaled** [comment]
Gonna leave this open so incoming users will know it's broken.

**Comment by alechenninger** [comment]
Ack, cool. I downgraded linter to 1.1.0 and no issues.

**Comment by devoncarew** [comment]
I suspect they changed their API for the linter:

https://github.com/AtomLinter/Linter/blob/a292cd757489d6a3ddc70a7e03c5d127e285b587/lib/linter-plus.coffee#L90

**Comment by radicaled** [comment]
It's the line below that: they're referencing a non-existent variable.

**Comment by radicaled** [comment]
Someone fudged a refactor, in other words.

**Comment by radicaled** [comment]
@alechenninger grab the newest dart-tools and it should be fixed. I've gone ahead and quickly upgraded to their working API

**Comment by alechenninger** [comment]
Thanks! With the latest version of linter and dart-tools running the analyzer works fine with no exceptions. :+1:

**Comment by radicaled** [comment]
Great! Now I'll close the issue. :)
